import {
	SunMedium,
	Moon,
	Laptop,
	MoreHorizontal,
	ArrowRight,
	Bot,
	X,
	Plus,
	Loader2,
	Languages,
	ArrowDownAZ,
	LayoutGrid,
	LayoutList,
	ArrowDownNarrowWide,
	ArrowDownWideNarrow,
	CalendarDays,
	Search,
	TerminalSquare,
	type Icon as LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
	Logo: Bot,
	Close: X,
	Sun: SunMedium,
	Moon: Moon,
	Laptop: Laptop,
	MoreHorizontal: MoreHorizontal,
	ArrowRight: ArrowRight,
	Plus: Plus,
	Loader: Loader2,
	Languages: Languages,
	ArrowDownAZ: ArrowDownAZ,
	LayoutGrid: LayoutGrid,
	LayoutList: LayoutList,
	ArrowDownNarrowWide: ArrowDownNarrowWide,
	ArrowDownWideNarrow: ArrowDownWideNarrow,
	CalendarDays: CalendarDays,
	Search: Search,
	TerminalSquare: TerminalSquare,
};
